### get blogs
GET http://localhost:3003/api/blogs

### add blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlYW51IiwiaWQiOiI2NDIzYmM2ZGY0MGY2MTdhZmJlNGVhOGYiLCJpYXQiOjE2ODA1MDk2NzR9.lLxJicDQmV7zKBWvDfJFPUnY4dWxmWQ5ZktbIb37lhE

{
    "title": "Token Taco",
    "author": "Berto",
    "url": "https://www.lipsum.com/",
    "likes": 7
}

### delete blog
DELETE http://localhost:3003/api/blogs/6401fa5fdce0043c5c33d790